# Generated by Django 4.0.3 on 2022-05-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
